import {
  Badge,
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
  Separator,
} from 'autoblogr'

export const Horizontal = () => (
  <div className="h-56 w-full max-w-2xl overflow-hidden rounded-lg border">
  <ResizablePanelGroup direction="horizontal">
    <ResizablePanel defaultSize={35}>
      <div className="h-full space-y-2 p-4">
        <p className="text-sm font-medium">Sites</p>
        <p className="text-sm text-muted-foreground">marketing-site.com</p>
        <p className="text-sm text-muted-foreground">blog.acme-docs.dev</p>
        <p className="text-sm text-muted-foreground">shop.northwind.io</p>
      </div>
    </ResizablePanel>
    <ResizableHandle withHandle />
    <ResizablePanel defaultSize={65}>
      <div className="h-full space-y-2 p-4">
        <p className="text-sm font-medium">Ten SEO mistakes to avoid</p>
        <p className="text-xs text-muted-foreground">1,240 words · SEO 87 · published 16 Jul 2026</p>
        <Separator />
        <p className="text-sm text-muted-foreground">
          Most technical SEO problems are self-inflicted. This post walks through the ten we see most
          often in audits, and what to change first.
        </p>
      </div>
    </ResizablePanel>
  </ResizablePanelGroup>
  </div>
)

export const Vertical = () => (
  <div className="h-56 w-full max-w-md overflow-hidden rounded-lg border">
  <ResizablePanelGroup direction="vertical">
    <ResizablePanel defaultSize={55}>
      <div className="h-full space-y-1 p-4">
        <p className="text-sm font-medium">Draft preview</p>
        <p className="text-sm text-muted-foreground">
          Crawl budget 101 — 1,610 words, generated by Claude Sonnet at 09:33.
        </p>
      </div>
    </ResizablePanel>
    <ResizableHandle withHandle />
    <ResizablePanel defaultSize={45}>
      <div className="h-full space-y-1 p-4 font-mono text-xs text-muted-foreground">
        <p>09:33:12 draft ok — 1,610 words</p>
        <p>09:33:20 wordpress 401 — auth failed</p>
        <p>09:33:20 run finished with 1 error</p>
      </div>
    </ResizablePanel>
  </ResizablePanelGroup>
  </div>
)

export const ThreePanels = () => (
  <div className="h-56 w-full max-w-2xl overflow-hidden rounded-lg border">
  <ResizablePanelGroup direction="horizontal">
    <ResizablePanel defaultSize={28}>
      <div className="h-full p-4">
        <p className="text-sm font-medium">Ideas</p>
        <p className="mt-2 text-xs text-muted-foreground">12 queued</p>
      </div>
    </ResizablePanel>
    <ResizableHandle withHandle />
    <ResizablePanel defaultSize={44}>
      <div className="h-full space-y-2 p-4">
        <div className="flex items-center justify-between gap-2">
          <p className="truncate text-sm font-medium">Crawl budget 101</p>
          <Badge variant="secondary">Draft</Badge>
        </div>
        <p className="text-xs text-muted-foreground">blog.acme-docs.dev · 1,610 words</p>
      </div>
    </ResizablePanel>
    <ResizableHandle withHandle />
    <ResizablePanel defaultSize={28}>
      <div className="h-full p-4">
        <p className="text-sm font-medium">SEO</p>
        <p className="mt-2 text-2xl font-semibold tabular-nums">74</p>
      </div>
    </ResizablePanel>
  </ResizablePanelGroup>
  </div>
)
