import { Label, Textarea } from 'autoblogr'

export const Basic = () => (
  <div className="flex max-w-md flex-col gap-2">
    <Label htmlFor="idea-brief">Content brief</Label>
    <Textarea
      id="idea-brief"
      rows={4}
      placeholder="Describe the angle, audience, and any keywords to target…"
    />
  </div>
)

export const WithValue = () => (
  <div className="flex max-w-md flex-col gap-2">
    <Label htmlFor="post-excerpt">Post excerpt</Label>
    <Textarea
      id="post-excerpt"
      rows={4}
      defaultValue="Most WordPress blogs stall because publishing is manual. This post walks through a three-step workflow that turns a keyword list into a scheduled draft, and shows where a human still needs to review before it goes live."
    />
    <p className="text-sm text-muted-foreground">Used as the meta description if none is set.</p>
  </div>
)

export const States = () => (
  <div className="grid max-w-md gap-4">
    <div className="flex flex-col gap-2">
      <Label htmlFor="ta-disabled">Disabled</Label>
      <Textarea id="ta-disabled" rows={2} disabled defaultValue="Connect a WordPress site to edit the brief." />
    </div>
    <div className="flex flex-col gap-2">
      <Label htmlFor="ta-readonly">Read only</Label>
      <Textarea
        id="ta-readonly"
        rows={2}
        readOnly
        defaultValue="Generated by google/gemini-2.5-pro on 14 Jul 2026 at 09:31."
      />
    </div>
    <div className="flex flex-col gap-2">
      <Label htmlFor="ta-error" className="text-destructive">
        Invalid
      </Label>
      <Textarea
        id="ta-error"
        rows={2}
        aria-invalid
        defaultValue="Write about coffee."
        className="border-destructive focus-visible:ring-destructive"
      />
      <p className="text-sm text-destructive">Briefs need at least 40 characters to generate a draft.</p>
    </div>
  </div>
)

export const SystemPrompt = () => (
  <div className="flex max-w-md flex-col gap-2">
    <div className="flex items-center justify-between">
      <Label htmlFor="tone-prompt">Tone instructions</Label>
      <span className="text-sm text-muted-foreground tabular-nums">118 / 500</span>
    </div>
    <Textarea
      id="tone-prompt"
      rows={5}
      className="font-mono text-sm"
      defaultValue="Write in a direct, practical voice. Short paragraphs, no filler intros. Address the reader as &quot;you&quot;. Never invent statistics."
    />
    <p className="text-sm text-muted-foreground">Prepended to every generation for this site.</p>
  </div>
)
